sonar.projectKey=seclock
sonar.projectName=seclock
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=venv/**,static/**,sample_certificates/**,test_e2e.py
sonar.tests=.
sonar.test.inclusions=test_e2e.py
sonar.python.version=3.12
